create table reservation(
    id int AUTO_INCREMENT not null primary key,
    product_type varchar(20) not null,
    product_location varchar(20) not null,
    title varchar(50) not null,
    price int not null default '0',
    detailed_location varchar(50) not null,
    recommended int not null default '0',
    acceptable_person int default '1',
    swimming_pool int default '0',
    karaoke int default '0',
    sauna int default '0',
    tables int default '0',
    washing_machine int default '0',
    dryer int default '0',
    cooking_possible int default '0',
    spa int default '0',
    fitness int default '0',
    thermal_springs int default '0',
    air_conditioner int default '0',
    shower int default '0',
    bathtub int default '0',
    wifi int default '0',
    tv int default '0',
    pc int default '0'
)